// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace UKP.Website.Controllers
{
    public partial class GuideController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected GuideController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult EpgInfo()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EpgInfo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult EpgDay()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EpgDay);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult EpgDateBar()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EpgDateBar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult EpgDayTab()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EpgDayTab);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public GuideController Actions { get { return MVC.Guide; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Guide";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Guide";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string EpgInfo = "EpgInfo";
            public readonly string EpgDay = "EpgDay";
            public readonly string EpgDateBar = "EpgDateBar";
            public readonly string EpgDayTab = "EpgDayTab";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string EpgInfo = "EpgInfo";
            public const string EpgDay = "EpgDay";
            public const string EpgDateBar = "EpgDateBar";
            public const string EpgDayTab = "EpgDayTab";
        }


        static readonly ActionParamsClass_EpgInfo s_params_EpgInfo = new ActionParamsClass_EpgInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EpgInfo EpgInfoParams { get { return s_params_EpgInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EpgInfo
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EpgDay s_params_EpgDay = new ActionParamsClass_EpgDay();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EpgDay EpgDayParams { get { return s_params_EpgDay; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EpgDay
        {
            public readonly string date = "date";
        }
        static readonly ActionParamsClass_EpgDateBar s_params_EpgDateBar = new ActionParamsClass_EpgDateBar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EpgDateBar EpgDateBarParams { get { return s_params_EpgDateBar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EpgDateBar
        {
            public readonly string date = "date";
        }
        static readonly ActionParamsClass_EpgDayTab s_params_EpgDayTab = new ActionParamsClass_EpgDayTab();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EpgDayTab EpgDayTabParams { get { return s_params_EpgDayTab; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EpgDayTab
        {
            public readonly string date = "date";
            public readonly string previousDay = "previousDay";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ChannelItems = "_ChannelItems";
                public readonly string _ChannelListing = "_ChannelListing";
                public readonly string _ChannelTimes = "_ChannelTimes";
                public readonly string _DateTab = "_DateTab";
                public readonly string _DateTabs = "_DateTabs";
                public readonly string _InfoPopup = "_InfoPopup";
                public readonly string Index = "Index";
            }
            public readonly string _ChannelItems = "~/Views/Guide/_ChannelItems.cshtml";
            public readonly string _ChannelListing = "~/Views/Guide/_ChannelListing.cshtml";
            public readonly string _ChannelTimes = "~/Views/Guide/_ChannelTimes.cshtml";
            public readonly string _DateTab = "~/Views/Guide/_DateTab.cshtml";
            public readonly string _DateTabs = "~/Views/Guide/_DateTabs.cshtml";
            public readonly string _InfoPopup = "~/Views/Guide/_InfoPopup.cshtml";
            public readonly string Index = "~/Views/Guide/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_GuideController : UKP.Website.Controllers.GuideController
    {
        public T4MVC_GuideController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EpgInfoOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, System.Guid id);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult EpgInfo(System.Guid id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EpgInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EpgInfoOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EpgDayOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string date);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult EpgDay(string date)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EpgDay);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "date", date);
            EpgDayOverride(callInfo, date);
            return callInfo;
        }

        [NonAction]
        partial void EpgDateBarOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string date);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult EpgDateBar(string date)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EpgDateBar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "date", date);
            EpgDateBarOverride(callInfo, date);
            return callInfo;
        }

        [NonAction]
        partial void EpgDayTabOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string date, bool previousDay);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult EpgDayTab(string date, bool previousDay)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EpgDayTab);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "date", date);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "previousDay", previousDay);
            EpgDayTabOverride(callInfo, date, previousDay);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
